name: CI

on:
  push:
    branches:
      - main
      - "release/*"
      - "hotfix/*"
      - "bugfix/*"
  pull_request:
    branches:
      - main

jobs:
  nx-affected:
    name: Nx Affected (Build, Typecheck)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Critical for Nx affected commands

      - name: Debug Git History
        run: |
          git log -n 5 --oneline
          git diff --name-only origin/main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: |
            .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('nx.json', '**/project.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Show Nx Workspace Projects
        run: npx nx show projects

      - name: Run Affected Type Check
        run: |
          npx nx print-affected --base=origin/main
          npx nx affected --target=typecheck --base=origin/main --parallel=3 --scan

      - name: Run Affected Build
        run: |
          npx nx print-affected --base=origin/main
          npx nx affected --target=build --base=origin/main --parallel=3 --scan
